/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.calculator.front.Componets;

import com.mycompany.calculator.back.Interpreter.Interpreter;
import com.mycompany.calculator.back.OperationCalculator.ArithmeticOperator;
import com.mycompany.calculator.back.ElementalFunctions.ArithmeticFunctions;

/**
 *
 * @author ASUS
 */
public class ArithmeticPanel extends javax.swing.JPanel {

    /**
     * Creates new form arithmeticPanel
     */
    public ArithmeticPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        variableA1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        variableA2 = new javax.swing.JTextField();
        additionButton = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        RestButton = new javax.swing.JButton();
        GreaterThanSingButton = new javax.swing.JButton();
        lessThanSignButton = new javax.swing.JButton();
        increaseButton = new javax.swing.JButton();
        GreaterThanOrEqualSingButton = new javax.swing.JButton();
        lessThanOrEqualSignButton = new javax.swing.JButton();
        decreaseButton = new javax.swing.JButton();
        resultadoA = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setText("Primer valor");

        variableA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableA1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Segundo valor");

        additionButton.setText("suma");
        additionButton.setPreferredSize(new java.awt.Dimension(105, 23));
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });

        subtractionButton.setText("resta");
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonActionPerformed(evt);
            }
        });

        multiplicationButton.setText("multiplicación");
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonActionPerformed(evt);
            }
        });

        divisionButton.setText("división");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        RestButton.setText("modulo");
        RestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestButtonActionPerformed(evt);
            }
        });

        GreaterThanSingButton.setText(">");
        GreaterThanSingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreaterThanSingButtonActionPerformed(evt);
            }
        });

        lessThanSignButton.setText("<");
        lessThanSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessThanSignButtonActionPerformed(evt);
            }
        });

        increaseButton.setText("+1");
        increaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseButtonActionPerformed(evt);
            }
        });

        GreaterThanOrEqualSingButton.setText("≥");
        GreaterThanOrEqualSingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreaterThanOrEqualSingButtonActionPerformed(evt);
            }
        });

        lessThanOrEqualSignButton.setText("≤");
        lessThanOrEqualSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessThanOrEqualSignButtonActionPerformed(evt);
            }
        });

        decreaseButton.setText("-1");
        decreaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseButtonActionPerformed(evt);
            }
        });

        resultadoA.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(variableA1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(variableA2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(RestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GreaterThanSingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lessThanSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(increaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GreaterThanOrEqualSingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lessThanOrEqualSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(decreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultadoA, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(variableA1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(variableA2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(additionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtractionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GreaterThanSingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessThanSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(increaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GreaterThanOrEqualSingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessThanOrEqualSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(resultadoA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void variableA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_variableA1ActionPerformed

    private void GreaterThanOrEqualSingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreaterThanOrEqualSingButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        double var1 = Double.parseDouble(valor1);
        double var2 = Double.parseDouble(valor2);
        boolean resultado = ArithmeticFunctions.greaterEqualTo(var1, var2);
        
        resultadoA.setText("" + resultado);
    }//GEN-LAST:event_GreaterThanOrEqualSingButtonActionPerformed

    private void lessThanOrEqualSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessThanOrEqualSignButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        double var1 = Double.parseDouble(valor1);
        double var2 = Double.parseDouble(valor2);
        boolean resultado = ArithmeticFunctions.minusEqualTo(var1, var2);
        
        resultadoA.setText("" + resultado);
    }//GEN-LAST:event_lessThanOrEqualSignButtonActionPerformed

    private void decreaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseButtonActionPerformed
        String valor1 = variableA1.getText();
        double var1 = Double.parseDouble(valor1);
        double resultado = ArithmeticFunctions.forwardUnitIncrement(var1);
        
        resultadoA.setText(""+resultado);
    }//GEN-LAST:event_decreaseButtonActionPerformed

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        
        double resultadoNumerico = (double) ArithmeticOperator.outPut(valor1, valor2, "+");
        String resultado = Double.toString(resultadoNumerico);
        
        resultadoA.setText(resultado);        
    }//GEN-LAST:event_additionButtonActionPerformed

    private void subtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        
        double resultadoNumerico = (double) ArithmeticOperator.outPut(valor1, valor2, "-");
        String resultado = Double.toString(resultadoNumerico);
        
        resultadoA.setText(resultado);     
    }//GEN-LAST:event_subtractionButtonActionPerformed

    private void multiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        
        double resultadoNumerico = (double) ArithmeticOperator.outPut(valor1, valor2, "*");
        String resultado = Double.toString(resultadoNumerico);
        
        resultadoA.setText(resultado);     
    }//GEN-LAST:event_multiplicationButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        
        double resultadoNumerico = (double) ArithmeticOperator.outPut(valor1, valor2, "/");
        String resultado = Double.toString(resultadoNumerico);
        
        resultadoA.setText(resultado);     
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void RestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        
        double resultadoNumerico = (double) ArithmeticOperator.outPut(valor1, valor2, "%");
        String resultado = Double.toString(resultadoNumerico);
        
        resultadoA.setText(resultado);     
    }//GEN-LAST:event_RestButtonActionPerformed

    private void GreaterThanSingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreaterThanSingButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        double var1 = Double.parseDouble(valor1);
        double var2 = Double.parseDouble(valor2);
        boolean resultado = ArithmeticFunctions.greaterTo(var1, var2);
        
        resultadoA.setText("" + resultado);
    }//GEN-LAST:event_GreaterThanSingButtonActionPerformed

    private void lessThanSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessThanSignButtonActionPerformed
        String valor1 = variableA1.getText();
        String valor2 = variableA2.getText();
        double var1 = Double.parseDouble(valor1);
        double var2 = Double.parseDouble(valor2);
        boolean resultado = ArithmeticFunctions.minusTo(var1, var2);
        
        resultadoA.setText("" + resultado);
    }//GEN-LAST:event_lessThanSignButtonActionPerformed

    private void increaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseButtonActionPerformed
        String valor1 = variableA1.getText();
        double var1 = Double.parseDouble(valor1);
        double resultado = ArithmeticFunctions.backwardUnitIncrement(var1);
        
        resultadoA.setText(""+resultado);
    }//GEN-LAST:event_increaseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GreaterThanOrEqualSingButton;
    private javax.swing.JButton GreaterThanSingButton;
    private javax.swing.JButton RestButton;
    private javax.swing.JButton additionButton;
    private javax.swing.JButton decreaseButton;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton increaseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lessThanOrEqualSignButton;
    private javax.swing.JButton lessThanSignButton;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JLabel resultadoA;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JTextField variableA1;
    private javax.swing.JTextField variableA2;
    // End of variables declaration//GEN-END:variables
}
